/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ApiClaraRouteImport } from './routes/api/clara'
import { Route as ApiPublicAgentsTickRouteImport } from './routes/api/public/agents-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaraRoute = ApiClaraRouteImport.update({
  id: '/api/clara',
  path: '/api/clara',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsTickRoute = ApiPublicAgentsTickRouteImport.update({
  id: '/api/public/agents-tick',
  path: '/api/public/agents-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/intake': typeof IntakeRoute
  '/plan': typeof PlanRoute
  '/api/clara': typeof ApiClaraRoute
  '/api/public/agents-tick': typeof ApiPublicAgentsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/intake': typeof IntakeRoute
  '/plan': typeof PlanRoute
  '/api/clara': typeof ApiClaraRoute
  '/api/public/agents-tick': typeof ApiPublicAgentsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/intake': typeof IntakeRoute
  '/plan': typeof PlanRoute
  '/api/clara': typeof ApiClaraRoute
  '/api/public/agents-tick': typeof ApiPublicAgentsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/agenda'
    | '/auth'
    | '/draft'
    | '/intake'
    | '/plan'
    | '/api/clara'
    | '/api/public/agents-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/agenda'
    | '/auth'
    | '/draft'
    | '/intake'
    | '/plan'
    | '/api/clara'
    | '/api/public/agents-tick'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/agenda'
    | '/auth'
    | '/draft'
    | '/intake'
    | '/plan'
    | '/api/clara'
    | '/api/public/agents-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  DraftRoute: typeof DraftRoute
  IntakeRoute: typeof IntakeRoute
  PlanRoute: typeof PlanRoute
  ApiClaraRoute: typeof ApiClaraRoute
  ApiPublicAgentsTickRoute: typeof ApiPublicAgentsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clara': {
      id: '/api/clara'
      path: '/api/clara'
      fullPath: '/api/clara'
      preLoaderRoute: typeof ApiClaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents-tick': {
      id: '/api/public/agents-tick'
      path: '/api/public/agents-tick'
      fullPath: '/api/public/agents-tick'
      preLoaderRoute: typeof ApiPublicAgentsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  DraftRoute: DraftRoute,
  IntakeRoute: IntakeRoute,
  PlanRoute: PlanRoute,
  ApiClaraRoute: ApiClaraRoute,
  ApiPublicAgentsTickRoute: ApiPublicAgentsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
