/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as ForksRouteImport } from './routes/forks'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ApiClaraRouteImport } from './routes/api/clara'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedSettingsBrandingRouteImport } from './routes/_authenticated/settings.branding'
import { Route as ApiPublicAgentsTickRouteImport } from './routes/api/public/agents-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ForksRoute = ForksRouteImport.update({
  id: '/forks',
  path: '/forks',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaraRoute = ApiClaraRouteImport.update({
  id: '/api/clara',
  path: '/api/clara',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBrandingRoute =
  AuthenticatedSettingsBrandingRouteImport.update({
    id: '/settings/branding',
    path: '/settings/branding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentsTickRoute = ApiPublicAgentsTickRouteImport.update({
  id: '/api/public/agents-tick',
  path: '/api/public/agents-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/forks': typeof ForksRoute
  '/intake': typeof IntakeRoute
  '/plan': typeof PlanRoute
  '/api/clara': typeof ApiClaraRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/api/public/agents-tick': typeof ApiPublicAgentsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/forks': typeof ForksRoute
  '/intake': typeof IntakeRoute
  '/plan': typeof PlanRoute
  '/api/clara': typeof ApiClaraRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/api/public/agents-tick': typeof ApiPublicAgentsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/actions': typeof ActionsRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/forks': typeof ForksRoute
  '/intake': typeof IntakeRoute
  '/plan': typeof PlanRoute
  '/api/clara': typeof ApiClaraRoute
  '/t/$slug': typeof TSlugRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/settings/branding': typeof AuthenticatedSettingsBrandingRoute
  '/api/public/agents-tick': typeof ApiPublicAgentsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/agenda'
    | '/auth'
    | '/draft'
    | '/forks'
    | '/intake'
    | '/plan'
    | '/api/clara'
    | '/t/$slug'
    | '/admin/tenants'
    | '/settings/branding'
    | '/api/public/agents-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/agenda'
    | '/auth'
    | '/draft'
    | '/forks'
    | '/intake'
    | '/plan'
    | '/api/clara'
    | '/t/$slug'
    | '/admin/tenants'
    | '/settings/branding'
    | '/api/public/agents-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/actions'
    | '/agenda'
    | '/auth'
    | '/draft'
    | '/forks'
    | '/intake'
    | '/plan'
    | '/api/clara'
    | '/t/$slug'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/settings/branding'
    | '/api/public/agents-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActionsRoute: typeof ActionsRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  DraftRoute: typeof DraftRoute
  ForksRoute: typeof ForksRoute
  IntakeRoute: typeof IntakeRoute
  PlanRoute: typeof PlanRoute
  ApiClaraRoute: typeof ApiClaraRoute
  TSlugRoute: typeof TSlugRoute
  ApiPublicAgentsTickRoute: typeof ApiPublicAgentsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forks': {
      id: '/forks'
      path: '/forks'
      fullPath: '/forks'
      preLoaderRoute: typeof ForksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clara': {
      id: '/api/clara'
      path: '/api/clara'
      fullPath: '/api/clara'
      preLoaderRoute: typeof ApiClaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/branding': {
      id: '/_authenticated/settings/branding'
      path: '/settings/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AuthenticatedSettingsBrandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agents-tick': {
      id: '/api/public/agents-tick'
      path: '/api/public/agents-tick'
      fullPath: '/api/public/agents-tick'
      preLoaderRoute: typeof ApiPublicAgentsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedSettingsBrandingRoute: typeof AuthenticatedSettingsBrandingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedSettingsBrandingRoute: AuthenticatedSettingsBrandingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActionsRoute: ActionsRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  DraftRoute: DraftRoute,
  ForksRoute: ForksRoute,
  IntakeRoute: IntakeRoute,
  PlanRoute: PlanRoute,
  ApiClaraRoute: ApiClaraRoute,
  TSlugRoute: TSlugRoute,
  ApiPublicAgentsTickRoute: ApiPublicAgentsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
